# Generated by Django 4.2.16 on 2024-11-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
