# Generated by Django 4.2.16 on 2024-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=255, null=True)),
                ('Reason', models.CharField(max_length=255, null=True)),
                ('Comment', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
